org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = true
org.gradle.caching = true

# the version is set as so to always have precedence over regular extra options, otherwise it has no special significance
mod_version = 2026.1.1

target_version = 1.16.1
archives_name = extra-options-ranked
maven_group = me.voidxwalker
