[versions]
minecraft = "1.2.5"
feather_build = "23"
nests_build = "9"
fabric_loader = "0.16.10"
loom = "1.10-SNAPSHOT"
ploceus = "1.10-SNAPSHOT"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "loom" }
ploceus = { id = "ploceus", version.ref = "ploceus" }
