[versions]
minecraft = "20w14infinite"
yarn_mappings = "20w14infinite+build.4"
fabric_loader = "0.15.11"
loom = "1.6-SNAPSHOT"
vineflower = "1.10.1"
# https://jitpack.io/#kingcontaria/speedrunapi
speedrunapi = "01eba12"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn_mappings = { module = "net.fabricmc:yarn", version.ref = "yarn_mappings" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
vineflower = { module = "org.vineflower:vineflower", version.ref = "vineflower" }
speedrunapi = { module = "dev.tildejustin:speedrunapi", version.ref = "speedrunapi" }

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "loom" }
