[versions]
minecraft = "1.15.2"
yarn_mappings = "1.15.2+build.17"
fabric_loader = "0.16.14"
loom = "1.10-SNAPSHOT"
# https://jitpack.io/#kingcontaria/speedrunapi
speedrunapi = "45fa51d142"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn_mappings = { module = "net.fabricmc:yarn", version.ref = "yarn_mappings" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
speedrunapi = { module = "com.github.contariaa:speedrunapi", version.ref = "speedrunapi" }

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "loom" }
